---
title: "Elementary Analysis on Interesting DataSets"
author: "Aman Das"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Overview

```{r}
setwd("~/Documents/Indian_Statistical_Institute/Sem_1/Statistical_Methods_1/Projects/Final_Sem/Test")
analyse = function(yearname, csv1, csv2){
  d1_raw = read.csv(csv1)
  d1 = d1_raw[!is.na(d1_raw[, yearname]),][,c("country", yearname)]
  d2_raw = read.csv(csv2)
  d2 = d2_raw[!is.na(d2_raw[, yearname]),][,c("country", yearname)]
  d3 = merge(x = d1, y = d2, by = "country")
  head(d3)
  
  x1 = d3[, paste(yearname, ".x", sep='')]
  x2 = d3[, paste(yearname, ".y", sep='')]
  # 
  # plot(density(x1), main = "Density Graph",
  #      xlim = c(-20, 120), ylim = c(0, 1/12), col = "dark green")
  # lines(density(x2), col = "dark red")
  # 
  # plot(ecdf(x1), main = "ECDF Graph",
  #      xlim = c(-20, 120), col = "dark green")
  # lines(ecdf(d3[, paste(yearname, ".y", sep='')]), col = "dark red")
  # 
  plot(x1, x2)
  cor(x1, x2)
}

```

## Water Supply Rural vs Agriculture employment

```{r}
yearname = "X2009"
analyse(yearname, "./Data/at_least_basic_water_source_rural_access_percent.csv", "./Data/agriculture_workers_percent_of_employment.csv")
```

## proportion of Government spending on health vs Life Expectancy
```{r}

analyse("X2010", "./Data/government_health_spending_of_total_gov_spending_percent.csv", "./Data/life_expectancy_years.csv")
```

## Sugar consumption vs Life Expectancy
```{r}
analyse("X2010", "./Data/sugar_per_person_g_per_day.csv", "./Data/life_expectancy_years.csv")
```

## Seafood consumption vs Life Expectancy
```{r}
analyse("X2010", "./Data/fisfod_cons_pc.csv", "./Data/life_expectancy_years.csv")
```

## Sugar consumption vs Fish Consumption
```{r}
analyse("X2010", "./Data/sugar_per_person_g_per_day.csv", "./Data/fisfod_cons_pc.csv")
```

## Seafood consumption vs Basic Sanitation
```{r}
analyse("X2010", "./Data/fisfod_cons_pc.csv", "./Data/at_least_basic_sanitation_overall_access_percent.csv")
```

## Basic Sanitation vs Life Expectancy
```{r}
analyse("X2010", "./Data/at_least_basic_sanitation_overall_access_percent.csv", "./Data/life_expectancy_years.csv")
```

## 